/* 首页卡墙的结果句文案 —— 第九轮（W7）落地，中文 33 条 + 第十轮补英文 28 条。
   与 seo.ts / seo-en.ts 的 description 分工：那一份给 <meta>，这一份给卡片。
   判据来自实量（dailybox-redesign/research/content.json）：参照每条描述是说完的一句话
   （句号率 0.93）、开头不重复（最高频 0.20）；直接搬 description 上墙时这两根是 0.00 与 1.00。
   事实一律来自该工具在 seo.ts / seo-en.ts 里真有的能力描述，这里只改写法，不新增能力主张。 */

export const CARD_COPY: Record<string, string> = {
  url: "把链接或表单里的特殊字符编成安全形式，也能还原成原文；encodeURIComponent、encodeURI、表单三种模式分开走。",
  qrcode: "文本或网址即刻生成二维码，尺寸、容错等级和前后景色都能自定义，确认后直接下载 PNG。",
  wordcount: "粘贴一段文字，字符数、去空格字符、单词数、行数和预计阅读时长同时出结果，中英文混排也能准确计数。",
  caseconvert: "整段文本在全部大写、全部小写、首字母大写、驼峰命名和下划线命名之间互转。",
  textcompare: "把两版文本放进去，逐行高亮新增、删除与修改并统计差异行数，代码、配置、文档版本比对都适用。",
  dedupe: "一键去除重复行、清理空行和首尾空格，再按字典序或长度排序，名单、关键词、数据列表很快整理干净。",
  fanjian: "简体转繁体、繁体转简体一键完成，用词习惯符合两岸规范，阅读、排版、跨境沟通都用得上。",
  textbinary: "文本转 01 二进制，也能把二进制还原回文本，支持中文 UTF-8 与自定义分隔符。",
  hash: "一次算出 MD5、SHA-1、SHA-256、SHA-384、SHA-512 五种摘要，用来核对文件有没有被改过。",
  regex: "写正则时实时高亮全部匹配，捕获组与命名分组单独列出，每个 token 的含义用中文解释。",
  uuid: "生成 v4 随机或 v7 时间有序的 UUID，也能出随机数，支持批量、大小写与连字符格式选项。",
  radix: "输入任意进制的数，2、8、10、16 四张卡实时联动，其余进制的等值立刻显示。",
  jwt: "拆开 JWT 的 header 与 payload，把 iat/nbf/exp 换成人能读的本地时间，过期状态直接标出来。",
  sql: "把挤成一行的 SQL 排成缩进清晰的格式，关键字大写、逗号换行、JOIN 缩进，SELECT 到 DELETE 都支持。",
  cron: "粘贴 cron 表达式，每个字段的含义翻成中文说明，并推算出接下来 5 次执行时间。",
  pdf: "在浏览器本地把多个 PDF 按顺序合并成一份，也能从单个文件抽取、拆分出指定页面。",
  pdftojpg: "用 pdf.js 在浏览器本地把 PDF 的每一页渲染成 JPG 或 PNG，文件不用上传。",
  jpgtopdf: "把多张 JPG、PNG 按顺序合成一个 PDF，可选贴合原图尺寸或统一 A4，横竖向和页边距都能调。",
  pdfrotate: "顺时针旋转整份文档或指定页面，90、180、270 度可选，每页当前角度实时预览。",
  pdforganize: "拖拽调整页面顺序、删除多余页、抽取需要的页，全程有实时缩略图预览。",
  pdfwatermark: "给 PDF 加文字或图片水印，透明度、角度、平铺都能调，中文 logo 和印章走图片水印。",
  pdfpagenum: "给 PDF 加页码，页眉页脚六个位置任选，格式支持 {n} 与 {total}，起始页码、字号颜色和首页是否显示都能定。",
  image: "批量压缩图片或转格式，JPG、PNG、WebP 互转，尺寸缩放与质量都能调。",
  video: "把视频压小或在 MP4、WebM 之间互转，也能剪切出片段，运算走 ffmpeg.wasm 在本地完成。",
  colorconvert: "一个颜色值进去，HEX、RGB、HSL 三种格式互转，带可视化取色器和实时预览，任一格式一键复制。",
  rmb: "金额转成中文大写，按财务规范处理零折叠、角分与整字，四舍五入到分，负数和超大金额都支持。",
  idcard: "按 GB 11643 校验位算法验证身份证号真伪，顺带解读省份、出生日期、性别与年龄。",
  unit: "长度、重量、面积、温度、数据量单位互转，输入一个数，所有单位的等值实时展示。",
  mortgage: "等额本息与等额本金两种算法一起出，逐期还款明细、总利息对比和提前还款测算都在同一页。",
  deposit: "算单利、复利的到期本息，做年化收益率换算和不同期限方案对比，用金融定义级公式计算。",
  irr: "把信用卡分期、网贷、消费贷的名义费率还原成真实年化 IRR，用迭代法精确求解内部收益率。",
  phone: "输入手机号查省份、城市和运营商，内置数十万条号段数据本地查询，支持批量。",
  lunar: "公历农历互转，天干地支、生肖、二十四节气和传统节日都能查，覆盖 1900 到 2100 年。",
};

/** EN 首页卡墙：28 条，与 seo-en.ts 的 slug 一一对应（本地化文本不翻译，直接按英文描述重写） */
export const CARD_COPY_EN: Record<string, string> = {
  url: "Encode or decode a link in three modes — encodeURIComponent, encodeURI or form — with Unicode and emoji preserved.",
  qrcode: "Turn text or a link into a QR code, set its size, error-correction level and colors, then download the PNG.",
  wordcount: "Count characters with and without spaces, words, lines and reading time as you type, across CJK and Latin alike.",
  caseconvert: "Switch text between UPPER, lower, Title case, camelCase and snake_case for code naming and cleanup.",
  textcompare: "Compare two versions line by line with added, deleted and changed highlights, plus a diff count.",
  dedupe: "Drop duplicate lines, clear blanks, trim edges and sort A–Z or by length in one pass, for lists and keyword sets.",
  textbinary: "Convert text into 01 and back again, UTF-8 safe for Chinese characters, with a separator you choose.",
  hash: "Get MD5, SHA-1, SHA-256, SHA-384 and SHA-512 digests as hex or base64 from one paste, computed by Web Crypto.",
  regex: "Test a regex with every match highlighted live, groups listed, and each token explained in plain English.",
  uuid: "Generate UUID v4 or time-ordered v7 in bulk, plus random numbers, from crypto-grade randomness with format options.",
  radix: "Type a number once and binary, octal, decimal and hex update together, with BigInt for huge values.",
  jwt: "Split a JWT into header and payload, read iat, nbf and exp as human times, and see the expiry flagged.",
  sql: "Beautify a one-line query into indented SQL with uppercased keywords — SELECT, INSERT, UPDATE and DELETE covered.",
  cron: "Paste a cron expression and get it in plain English, field by field, along with the next five run times.",
  pdf: "Merge several PDFs in the order you choose, or pull a page range out into a new file, with pdf-lib in the browser.",
  image: "Compress or convert JPG, PNG and WebP in bulk, with resize and quality controls on Canvas.",
  video: "Shrink or convert MP4 and WebM, or cut out a clip, with ffmpeg.wasm on your machine.",
  pdfrotate: "Rotate the whole document or only the pages you pick by 90, 180 or 270 degrees, each angle previewed.",
  pdforganize: "Reorder, delete or extract pages over live thumbnails, then export a new PDF and leave the original untouched.",
  pdfwatermark: "Lay text or an image logo across all or selected pages, with size, color, opacity, rotation and tiling.",
  pdfpagenum: "Number pages in six header/footer positions, with a {n} / {total} format, start value, size, color and skip-first.",
  pdftojpg: "Render every page of a PDF to JPG or PNG with pdf.js, adjust scale and background, then take one page or a ZIP of all.",
  jpgtopdf: "Combine JPG and PNG images into one PDF in order, fitted to their own size or a uniform A4 page.",
  colorconvert: "Paste one color and get HEX, RGB and HSL side by side, with a visual picker, live preview and one-click copy.",
  unit: "Convert length, weight, area, temperature and data size, imperial included — every equal value shows as you type.",
  mortgage: "See annuity and equal-principal plans with a period-by-period schedule, interest totals and prepayment estimates.",
  deposit: "Work out the maturity value under simple or compound interest, annualize the yield and compare term options.",
  irr: "Reveal the true annual cost of credit-card installments and consumer loans by solving their internal rate of return.",
};
